Attribute VB_Name = "modEnumerations"
Option Explicit

Public Enum SPackets
    Smaxinfo = 1
    Snpchp
    Salertmsg
    Splainmsg
    Sallchars
    Sloginok
    Snews
    Snewcharclasses
    Sclassesdata
    Splayernewxy
    Stotalonline
    Singame
    Splayerinv
    Splayerinvupdate
    Splayerbank
    Splayerbankupdate
    Sopenbank
    Sbankmsg
    Splayerworneq
    Splayerequipupdate
    Splayerpoints
    Sstatpointused
    Splayerhp
    Splayermp
    Splayersp
    Splayerexp
    Smapmsg2
    Splayerstatspacket
    Smsgbox
    Sfavor
    Scardshop
    Supdatecardshop
    Splayerdata
    Smapplayersinbattle
    Sleave
    Sleft
    Swelcomemsg
    Sfriendstatus
    Scaption
    Splayerlevel
    Splayermove
    Snpcmove
    Splayerdir
    Snpcdir
    Splayerxy
    Sattack
    Snpcattack
    Scheckformap
    Smapdata
    Smapitemdata
    Smapnpcdata
    Smapdone
    Sturnbasedtime
    Sglobalmsg
    Splayermsg
    Sothermsg
    Smapmsg
    Sadminmsg
    Sspawnitem
    Sitemeditor
    Supdateitem
    Sedititem
    Sspawnnpc
    Snpcdead
    Snpceditor
    Snpctalk
    Snpctalkyesno
    Supdatenpc
    Seditnpc
    Srecipeeditor
    Supdaterecipe
    Seditrecipe
    Scookitem
    Scooking
    Srecipelog
    Smapkey
    Seditmap
    Sshopeditor
    Supdateshop
    Seditshop
    Sspelleditor
    Supdatespell
    Seditspell
    Sgoshop
    Sspells
    Sspecialattackinfo
    Sweather
    Sonlinelist
    Sguildmemberrequest
    Sgroupmemberlist
    Sblitplayerdmg
    Sblitnpcdmg
    Straderequest
    Sstarttrade
    Sstoptrading
    Supdatetradeoffers
    Strademessage
    Sppchatting
    Sqchat
    Ssendchat
    Ssound
    Sprompt
    Squerybox
    Sturnbasedbattle
    Sturnbasedvictory
    Semoticoneditor
    Seditemoticon
    Supdateemoticon
    Selementeditor
    Seditelement
    Supdateelement
    Sarroweditor
    Seditarrow
    Supdatearrow
    Shookshot
    Scheckarrows
    Schecksprite
    Smapreport
    Sspellanim
    Sscriptspellanim
    Scheckemoticons
    Slevelup
    Sdamagedisplay
    Sitemworn
    Scanusespecial
    Splayerheight
    Sjumping
    Sendjump
    Shiderfreeze
    Shidensneak
    Server_Count
End Enum

Public Enum CPackets
    Cgetclasses = 1
    Cnewaccount
    Cdelaccount
    Cacclogin
    Cgivemethemax
    Caddchar
    Cdelchar
    Cusechar
    Cguildchangeaccess
    Cguilddisown
    Cguildleave
    Cguildmake
    Cguildmember
    Cguildmemberrequest
    Cguildmemberdecline
    Cguildtrainee
    Cgroupmemberlist
    Csaymsg
    Cgroupmsg
    Cmapmsg
    Cbroadcastmsg
    Cglobalmsg
    Cadminmsg
    Cplayermsg
    Cothermsg
    Cplayermove
    Cplayerdir
    Cuseitem
    Cplayermovemouse
    Cwarp
    Cattack
    Cusestatpoint
    Csetplayersprite
    Cgetstats
    Crequestnewmap
    Cwarpmeto
    Cwarptome
    Cmapdata
    Cneedmap
    Cmapgetitem
    Cmapdropitem
    Cmaprespawn
    Ckickplayer
    Cmuteplayer
    Cunmuteplayer
    Cgetmutelist
    Cgetbanlist
    Cbanplayer
    Cunbanplayer
    Crequesteditmap
    Crequestedititem
    Cedititem
    Csaveitem
    Crequesteditnpc
    Ceditnpc
    Csavenpc
    Crequesteditshop
    Ceditshop
    Csaveshop
    Crequesteditspell
    Ceditspell
    Csavespell
    Cforgetspell
    Cspecialattackdetails
    Csetaccess
    Conlinelist
    Csetmotd
    Cbuy
    Csellitem
    Csearch
    Cplayerchat
    Cachat
    Cdchat
    Cqchat
    Csendchat
    Ctraderequest
    Caccepttrade
    Cdeclinetrade
    Cstoptrading
    Cupdatetradeoffers
    Ccompletetrade
    Cparty
    Cjoinparty
    Cpartydecline
    Cleaveparty
    Cspells
    Chotscript
    Ccast
    Cprompt
    Cquerybox
    Crequesteditarrow
    Ceditarrow
    Csavearrow
    Crequesteditemoticon
    Crequesteditelement
    Ceditemoticon
    Ceditelement
    Csaveemoticon
    Csaveelement
    Ccheckemoticons
    Cmapreport
    Cweather
    Cwarpto
    Clocalwarp
    Cmakeadmin
    Carrowhit
    Carrowswitch
    Cbankdeposit
    Cbankwithdraw
    Cbankdestroy
    Cgetonline
    Cdragdropinv
    Crunfrombattle
    Chasturnbased
    Csetbattleturn
    Cstartbattle
    Cuseturnbaseditem
    Crequesteditrecipe
    Ceditrecipe
    Csaverecipe
    Ccookitem
    Ccooking
    Cfriendonlineoffline
    Ccaption
    Cwarn
    Cremovewarn
    Ccardshop
    Cunequip
    Cuseturnbasedspecial
    Cfinishplayerbattle
    Chelp
    Cplayerheight
    Cjumping
    Cendjump
    Cusespecialbadge
    Cdodgebillspawn
    Cnotifyotherplayer
    Cjugemscloudwarp
    Cgetplayerinfo
    Cdoctorheal
    Client_Count
End Enum

